### ISSUE TITLE
Cannot import if package has `type="module"`

### ISSUE THREAD

**Issue by ThornWalli** [marcellkiss/rxjs-observable-queue#1]
Hello,

Great Package 🎉

Unfortunately I have problem when embedding in Node (`19.9.0`). 
Have an existing project with `type: 'module'` and get the error when importing: 

```
import { ObservableQueue } from 'rxjs-observable-queue';
         ^^^^^^^^^^^^^^^
SyntaxError: Named export 'ObservableQueue' not found. The requested module 'rxjs-observable-queue' is a CommonJS module, which may not support all module.exports as named exports.
```

**Comment by marcellkiss** [comment]
Hey @ThornWalli , thanks for letting me know, in version 1.0.18 it should be resolved, pls let me know if it's not the case

**Comment by ThornWalli** [comment]
Thanks!
